[project]
name = "mcp-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apache-airflow>=3.1.6",
    "fastmcp>=2.14.3",
    "langchain>=1.2.6",
    "mcp[cli]>=1.25.0",
    "pymongo[srv]>=4.16.0",
]
